# Hisilicon IPP v250 Makefile

obj-$(CONFIG_HISPIPP_V250) += cpetop.o
obj-$(CONFIG_HISPIPP_V250) += mcf.o
obj-$(CONFIG_HISPIPP_V250) += mfnr.o
obj-$(CONFIG_HISPIPP_V250) += slam.o
obj-$(CONFIG_HISPIPP_V250) += vbk.o
obj-$(CONFIG_HISPIPP_V250) += reorder.o
obj-$(CONFIG_HISPIPP_V250) += compare.o
