#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_ST_TS_KIT_3_0) += fts.o
#obj-$(CONFIG_ST_TS_KIT_3_0) += fts_proc.o
obj-$(CONFIG_ST_TS_KIT_3_0) += fts_lib/
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include