#
# Makefile for hisilicon pmic sensor driver
#

obj-y += hw_pmic.o
obj-$(CONFIG_HUAWEI_CAMERA_PMIC_RT5112) += rt5112.o
obj-$(CONFIG_HUAWEI_CAMERA_PMIC_FAN53880) += fan53880.o
ccflags-y += -Idrivers/media/huawei/camera/pmic
