obj-$(CONFIG_HISI_SOH)      += hisi_soh_core.o
obj-$(CONFIG_HISI_SOH_PMIC) += pmic/
obj-$(CONFIG_HISI_SOH_HI6531) += hi6531/
obj-$(CONFIG_HISI_SOH_CHARGER) += hi6526/
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver/libhwsecurec/
