#
# Logger extend configuration
#

obj-$(CONFIG_LOG_EXCEPTION)	+= log_exception.o
obj-$(CONFIG_LOG_EXCEPTION)	+= log_usertype.o
obj-$(CONFIG_LOG_EXCEPTION)	+= imonitor_events.o
obj-$(CONFIG_HWLOG_KERNEL)	+= hwlog_kernel.o
obj-$(CONFIG_HIVIEW_SELINUX)	+= hiview_selinux.o
