#
# Copyright (c) Huawei Technologies Co., Ltd. 2018-2018. All rights reserved.
# Description: Makefile for the KERNEL STP
# Author: sunhongqing <sunhongqing@huawei.com>
# Create: 2018-03-31
#

obj-$(CONFIG_HW_KERNEL_STP) += hw_kernel_stp_module.o hw_kernel_stp_proc.o     \
			hw_kernel_stp_scanner.o hw_kernel_stp_uploader.o
