#
# Makefile for the KERNEL STP
#
# sunhongqing <sunhongqing@huawei.com>
#
# Copyright (c) 2017-2021, Huawei Tech. Co., Ltd. All rights reserved.
#

obj-$(CONFIG_HW_KERNEL_STP) += hw_kernel_stp_module.o hw_kernel_stp_proc.o hw_kernel_stp_scanner.o hw_kernel_stp_uploader.o
