# ELAN
obj-$(CONFIG_ELAN_TS_KIT_3_0) += elan_ts.o
obj-$(CONFIG_ELAN_TS_KIT_3_0) += elan_mmi.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include
