# Makefile for the storage_rofa modules.

obj-$(CONFIG_HUAWEI_DYNAMIC_BRD)    += ramdisk/
obj-$(CONFIG_HUAWEI_STORAGE_ROFA)   += storage_rochk/
obj-$(CONFIG_HUAWEI_STORAGE_ROFA)   += storage_row/
obj-$(CONFIG_HUAWEI_STORAGE_ROFA)   += storage_rofa.o
