#
# Makefile for hisilicon camera mcu driver
#
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/fpga/stm32
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/fpga
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_HISI_CAMERA_FPGA_STM32) += stm32_spi.o
obj-$(CONFIG_HISI_CAMERA_FPGA_STM32) += stm32.o
