# maxim smartPA driver

obj-$(CONFIG_ANC_HS_MODULE) += anc_hs_module/
obj-$(CONFIG_INVERT_HS) += invert_hs/
obj-$(CONFIG_TFA9895) += tfa9895/
obj-$(CONFIG_SND_SOC_TAS2560) += tas2560/
obj-$(CONFIG_TFA98XX) += tfa98xx/
obj-$(CONFIG_MAXIM)	+= maxim/
obj-$(CONFIG_AK4376)	+= ak4376/
obj-$(CONFIG_AK4376_KERNEL_4_1)	+= ak4376-kernel-4-1/
obj-$(CONFIG_HIFI_VIR_DAI)	+= hifi_vir_dai/
obj-$(CONFIG_USB_ANALOG_HS_MODULE)	+= usb_analog_hs_module/
obj-$(CONFIG_USB_AUDIO_POWER)	+= usb_audio_power/
obj-$(CONFIG_USB_AUDIO_COMMON)	+= usb_audio_common/
obj-$(CONFIG_USB_AUDIO_POWER_V600) += usb_audio_power_v600/
obj-$(CONFIG_USB_AUDIO_POWER)	+= usb_headset_core/
obj-$(CONFIG_HIGH_RESISTANCE_HS_DET) += high_resistance_hs_det/
