
#ifndef _HWAA_LIMITS_H
#define _HWAA_LIMITS_H

#ifdef __KERNEL__
#include <linux/limits.h>
#else
#include <sys/limits.h>
#endif

#ifndef HWAA_USER_KEY_DESC_MIN
#define HWAA_USER_KEY_DESC_MIN 1
#endif

#ifndef HWAA_USER_KEY_DESC_MAX
#define HWAA_USER_KEY_DESC_MAX 8
#endif

#ifndef HWAA_PACKAGE_NAME_MIN
#define HWAA_PACKAGE_NAME_MIN 1
#endif

#ifndef HWAA_PACKAGE_NAME_MAX
#define HWAA_PACKAGE_NAME_MAX NAME_MAX
#endif

#ifndef HWAA_PACKAGE_SIGNER_MIN
#define HWAA_PACKAGE_SIGNER_MIN 1
#endif

#ifndef HWAA_PACKAGE_SIGNER_MAX
#define HWAA_PACKAGE_SIGNER_MAX 4096
#endif

#ifndef HWAA_PACKAGE_SIG_MIN
#define HWAA_PACKAGE_SIG_MIN 1
#endif

#ifndef HWAA_PACKAGE_SIG_MAX
#define HWAA_PACKAGE_SIG_MAX 4096
#endif

#ifndef HWAA_PACKAGE_SHUID_MIN
#define HWAA_PACKAGE_SHUID_MIN 1
#endif

#ifndef HWAA_PACKAGE_SHUID_MAX
#define HWAA_PACKAGE_SHUID_MAX NAME_MAX
#endif

#ifndef HWAA_POLICY_RULESET_MIN
#define HWAA_POLICY_RULESET_MIN 10
#endif

#ifndef HWAA_POLICY_RULESET_MAX
#define HWAA_POLICY_RULESET_MAX 256
#endif

#ifndef HWAA_ENCODED_WFEK_SIZE
#define HWAA_ENCODED_WFEK_SIZE 251
#endif

#ifndef HWAA_FEK_SIZE_MAX
#define HWAA_FEK_SIZE_MAX 64
#define HWAA_FEK_SIZE 64
#endif

#ifndef HWAA_PERMISSION_GROUPS
#define HWAA_PERMISSION_GROUPS 4
#define HWAA_PERMISSION_GROUPS_RESERVED 4
#endif

#ifndef HWAA_AES_IV_LENGTH
#define HWAA_AES_IV_LENGTH 16
#endif

#endif
