
#ifndef _HWAA_ERROR_H
#define _HWAA_ERROR_H

/* return codes */
typedef enum {
	HWAA_SUCCESS,
	HWAA_ERR_INTERNAL = 900001,
	HWAA_ERR_USER_ALREADY_EXISTS,
	HWAA_ERR_UNKNOWN_USER,
	HWAA_ERR_UNATHENTICATED,
	HWAA_ERR_NO_MEMORY,
	HWAA_ERR_INVALID_ARGS,
	HWAA_ERR_INVALID_TOKEN,
	HWAA_ERR_INVALID_PERMS_RID,
	HWAA_ERR_INVALID_KEY,
	HWAA_ERR_REQUEST_TIMEOUT,
	HWAA_ERR_ACCESS_DENIED,
	HWAA_ERR_UNKNOWN_PACKAGE,
	HWAA_ERR_NOT_SUPPORTED,
	HWAA_ERR_NO_FS_CALLBACKS,
	HWAA_ERR_PID_NOT_TRUST,
	HWAA_ERR_UID_NOT_TRUST,
	HWAA_ERR_NOT_UPDATE_PERM,
	HWAA_ERR_GET_XATTR,
	HWAA_ERR_TAG_NOT_MATCH,
	HWAA_ERR_NOT_OWNER,
	HWAA_ERR_HKDF_EXTRACT,
	HWAA_ERR_HKDF_EXPAND,
} hwaa_result_t;

#endif
